---
- hosts: test-server
  become: true
  tasks:
    - name: update cache
      apt:
        update_cache: yes

    - name: install docker runtime
      apt:
        pkg: docker.io
        state: present

    - name: start docker service
      service:
        name: docker
        state: started
        enabled: true
      
    - name: Deploy finance-me app
      command: docker run -itd -p 8081:8081 vaibhav123pathak/finance-me:1.0 

